version: '3'
services:
    back:
      build:
        context: ./back
      restart: always
      network_mode: bridge
      ports:
        - 5000:5000
      volumes:
        - ./back/resources:/back/resources
    front:
      build: 
        context: ./front
      stdin_open: true
      tty: true
      restart: always
      network_mode: bridge
      ports:
            - "8081:80"
